[build]
builder = "dockerfile"
dockerfilePath = "../../../Dockerfile.user-service"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
